# Generated by Django 4.1.5 on 2023-01-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0002_alter_gi_name_alter_gi_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="gi",
            name="photo",
            field=models.ImageField(null=True, upload_to="gi_photos"),
        ),
        migrations.AlterField(
            model_name="gi",
            name="color",
            field=models.CharField(
                choices=[
                    ("Black", "Black"),
                    ("White", "White"),
                    ("Blue", "Blue"),
                    ("Bright", "Bright"),
                    ("Dark", "Dark"),
                ],
                max_length=15,
            ),
        ),
    ]
